api:
  on_client_connected:
    - esp32_ble_tracker.start_scan:
        continuous: true
  on_client_disconnected:
    if:
      condition:
        not:
          api.connected:
      then:
        - esp32_ble_tracker.stop_scan:

bluetooth_proxy:
  id: bt_proxy
  active: true

esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    active: false
    continuous: false

select:
  - platform: template
    name: Bluetooth Scanner Mode
    id: scanner_mode
    options:
      - "Passive"
      - "Active"
    lambda: |-
      if (id(ble_tracker).get_scan_active()) {
        return {"Active"};
      } else {
        return {"Passive"};
      }
    set_action:
      - lambda: |-
          id(bt_proxy).bluetooth_scanner_set_mode(x == "Active");
      - component.update: scanner_mode
