packages:
  bed-presence-mk1: !include bed-presence-mk1.yaml
  
esphome:
  project:
    name: ElevatedSensors.BedPresenceMk1
    version: "2024.8.5"

# Allow Import
dashboard_import:
  package_import_url: github://ElevatedSensors/sensor-configs/bed-presence-mk1.yaml@main
  import_full_config: true

# Managed updates from Elevated Sensors (future)
ota:
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    id: update_http_request
    name: Firmware
    source: https://docs.elevatedsensors.com/bpmk1-manifest.json
    update_interval: 10s   # TODO update to 6 hours after dev work

http_request:
  verify_ssl: true
