substitutions:
  name: bed-presence
  friendly_name: Bed Presence

  # Auto Calibrate Trigger Percentile
  # This controls how the trigger threshold is set when auto calibration is enabled. This is the percentage of the
  # observed pressure that is required to register the bed as occupied. During auto calibration, the system stores the
  # minimum and maximum pressures that it sees and used those values in combination with the trigger_percentile to
  # calculate the trigger threshold.
  #     - 0.9    Less sensitive, requires 90% of the maximum measured pressure to trigger (Default)
  #     - 0.50   Set trigger exactly in the middle of minimum and maximum measured pressures
  #     - 0.20   More sensitive, likely to be triggered by partner
  trigger_percentile: '0.90'
  build_test: '5'

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ElevatedSensors.BedPresenceMk1
    version: "2024.7.0"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Allow Import
dashboard_import:
  package_import_url: github://ElevatedSensors/sensor-configs/bed-presence-mk1.yaml@main
  import_full_config: true

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

# Enable esphome OTA updates
ota:
  platform: esphome

## Managed Updates from Elevated Sensors
#ota:
#- platform: http_request
#
#http_request:
#  verify_ssl: false
#
#update:
#  - platform: http_request
#    name: Firmware Update
#    source: https://dev.elevatedsensors.com/sensor-configs-/manifest.json
#    update_interval: 6h

################################################################################
packages:
  remote_package:
    url: https://github.com/ElevatedSensors/sensor-configs
    ref: main
    files: ['bed-presence-mk1/base.yaml']
    refresh: 1s
