name: Build and Publish ESPHome firmware

on:
  workflow_call:
    inputs:
      files:
        description: Comma-separated list of files to build.
        required: true
        type: string
      name:
        description: Name of the firmware to publish.
        required: false
        type: string
        default: ESPHome
      clean:
        description: Remove deleted files from the build
        required: false
        type: boolean
        default: true
      manifest_filename:
        description: Filename of the manifest to write.
        required: false
        type: string
        default: manifest.json
      esphome_version:
        description: Version of ESPHome to build for.
        required: false
        type: string
        default: latest
      build_fw:
        description: Build the firmware
        required: false
        type: boolean
        default: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files-array.outputs.files }}
    steps:
      - id: files-array
        run: |
          files=$(echo "${{ inputs.files }}" | jq -Rcn 'inputs | . / ","')
          echo files=$files >> $GITHUB_OUTPUT
          mkdir output

  build:
    name: Build ESPHome binary for ${{ matrix.file }}
    if: ${{ inputs.build_fw }}  # Don't build if there haven't been any fw changes
    needs: [prepare]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.prepare.outputs.files) }}
    outputs:
      esphome-version: ${{ steps.esphome-build.outputs.esphome-version }}
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: esphome/build-action@v3.1.0
        id: esphome-build
        with:
          yaml_file: ${{ matrix.file }}
          version: ${{ inputs.esphome_version }}
      - run: |
          mv "${{ steps.esphome-build.outputs.name }}" output/
        run: |
          jq -s '{"name": "${{ inputs.name }}", "version": "${{ steps.esphome-build.outputs.esphome-version }}", "home_assistant_domain": "esphome", "new_install_skip_erase": false, "builds":.}' output/*/manifest.json > output/${{ inputs.manifest_filename }}
      - uses: actions/upload-artifact@v4.3.4
        with:
          name: ${{ inputs.name }}
          path: output

            #package:
            #  name: Package up manifest.json
            #  if: ${{ inputs.build_fw }}
            #  runs-on: ubuntu-latest
            #  needs: [build]
            #  steps:
            #    - uses: actions/download-artifact@v4.1.8
            #      with:
            #        path: output
            #        name: ${{ inputs.name }}

            #    - name: Create single manifest.json
            #      run: |
            #        jq -s '{"name": "${{ inputs.name }}", "version": "${{ needs.build.outputs.esphome-version }}", "home_assistant_domain": "esphome", "new_install_skip_erase": false, "builds":.}' output/*/manifest.json > output/${{ inputs.manifest_filename }}


  publish:
    name: Publish new firmware and website to GitHub Pages
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/download-artifact@v4.1.8
        with:
          path: output
          name: ${{ inputs.name }}
        continue-on-error: true

      - run: cp -R static/* output

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: gh-pages
          folder: output
          clean: ${{ inputs.clean }}
