name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main
    paths:
      - 'bed-presence-mk1.yaml'

jobs:
  build:
    uses: ./actions/build-fw.yml@main
    with:
      files: bed-presence-mk1.yaml
      name: Bed Presence Mk1
      version: 2024.6.6

  publish:
    uses: ./actions/publish-pages.yml@main
    with:
      name: Bed Presence Mk1
      version: 2024.6.6

