name: Bed Presence Mk1 Firmware Changed

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'bed-presence-mk1.factory.yaml'
  #     - 'bed-presence-mk1.yaml'
  #     - 'bed-presence-mk1/*.yaml'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/action-build-and-publish.yml
    with:
      files: bed-presence-mk1.factory.yaml
      name: Bed Presence Mk1
      esphome-version: latest
      manifest-filename: bpmk1-manifest.json
      release-url: https://docs.elevatedsensors.com/bed-presence-mk1/release
