name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main
    paths:
      - 'bed-presence-mk1.yaml'

jobs:
  build:
    uses: ./.github/workflows/action-build-and-publish.yml
    with:
      files: bed-presence-mk1.yaml
      name: Bed Presence Mk1
      esphome_version: 2024.6.6

