name: Bed Presence Mk1 Firmware Changed

on:
  push:
    branches:
      - main
    paths:
      - 'test.yaml'

jobs:
  build:
    uses: ./.github/workflows/action-build-and-publish.yml
    with:
      files: test.yaml
      name: Test
      esphome_version: latest
      manifest_filename: test-manifest.json
