name: Bed Presence Mk1 Firmware Changed

on:
  push:
    branches:
      - main
    paths:
      - 'bed-presence-mk1.factory.yaml'
      - 'bed-presence-mk1.yaml'
      - 'bed-presence-mk1/*.yaml'
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Get release info
        id: release-info
        uses: jbutcher5/read-yaml@1.6
        with:
          file: bed-presence-mk1/release-info.yaml
          key-path: '["release-summary", "release-url"]'
      - run: echo "${{ steps.release-info.outputs.data }}"
      - run: echo "${{ steps.release-info.outputs.data.release-summary }}"
      - run: echo "${{ steps.release-info.outputs.data.release-url }}"
      - name: Build and Publish
        uses: ./.github/workflows/action-build-and-publish.yml
        with:
          files: bed-presence-mk1.factory.yaml
          name: Bed Presence Mk1
          esphome-version: latest
          manifest-filename: bpmk1-manifest.json
