name: Publish ESPHome website

on:
  push:
    branches:
      - main
    paths:
      - 'static/**'

jobs:
  publish:
    uses: ./.github/workflows/action-build-and-publish.yml
    with:
      files: bed-presence-mk1.yaml
      name: Bed Presence Mk1
      build_fw: false

