name: Publish ESPHome website (don't rebuild fw)

on:
  push:
    branches:
      - main
    paths:
      - 'static/**'

jobs:
  publish:
    uses: ./.github/workflows/action-publish-pages.yml
    with:
      name: Bed Presence Mk1
      esphome_version: 2024.6.6

